### ISSUE TITLE
Error : Spawn java ENOENT

### ISSUE THREAD

**Issue by chiubaca** [Esri/esri-wab-build#53]
I'm getting the following error trying to build an app from WAB 2.9 . Hope you are able to help.
```
starting parsing resource...
{ Error: spawn java ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs:
   [ '-cp',
     'D:\\WABForArcGIS\\arcgis-web-appbuilder-2.9\\WebAppBuilderForArcGIS\\server\\apps\\dist\\build-src\\util\\closureCompiler\\compiler.jar;D:\\WABForArcGIS\\arcgis-web-appbuilder-2.9\\WebAppBuilderForArcGIS\\server\\apps\\dist\\build-src\\util\\shrinksafe\\js.jar;D:\\WABForArcGIS\\arcgis-web-appbuilder-2.9\\WebAppBuilderForArcGIS\\server\\apps\\dist\\build-src\\util\\shrinksafe\\shrinksafe.jar',
     'org.mozilla.javascript.tools.shell.Main',
     'D:\\WABForArcGIS\\arcgis-web-appbuilder-2.9\\WebAppBuilderForArcGIS\\server\\apps\\dist\\build-src\\util\\build\\optimizeRunner.js' ] }
Error: spawn java ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
build always "fails"
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'D:\WABForArcGIS\arcgis-web-appbuilder-2.9\WebAppBuilderForArcGIS\server\apps\dist\buildOutput\app-packages'
    at Object.fs.readdirSync (fs.js:904:18)
    at visitFolderFiles (C:\Users\Alex\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:573:18)
    at Object.cleanUncompressedSource (C:\Users\Alex\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:772:3)
    at Object.exports.copy (C:\Users\Alex\AppData\Roaming\npm\node_modules\esri-wab-build\app\copyapp.js:21:17)
    at Object.exports.build (C:\Users\Alex\AppData\Roaming\npm\node_modules\esri-wab-build\app\buildTool.js:120:14)
    at Object.exports.buildApp (C:\Users\Alex\AppData\Roaming\npm\node_modules\esri-wab-build\app\remoteBuild.js:20:13)
    at Object.<anonymous> (C:\Users\Alex\AppData\Roaming\npm\node_modules\esri-wab-build\app\build:12:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```
im using:
node v8.11.3
java 8
bower 1.8.4

**Comment by chiubaca** [comment]
Ok, so I've managed to get this to work on a WAB application from 2.7 . Is support for 2.9 coming soon?

**Comment by gbochenek** [comment]
We will likely have to change up the includes in https://github.com/gbochenek/esri-wab-build/blob/master/app/_app.profile.js to get the upgrade working.  Sometimes the jimu classes change at upgrade time.

**Comment by DemersM** [comment]
I have a similar error with WAB 2.9. Is it suppose to works with 2.9 ? Is there a fix?

```
{ Error: spawn java ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn java',
  path: 'java',
  spawnargs:
   [ '-cp',
     'C:\\Users\\ville_service\\dist\\build-src\\util\\closureCompiler\\compiler.jar;C:\\Users\\ville_service\\dist\\build-src\\util\\shrink
safe\\js.jar;C:\\Users\\ville_service\\dist\\build-src\\util\\shrinksafe\\shrinksafe.jar',
     'org.mozilla.javascript.tools.shell.Main',
     'C:\\Users\\ville_service\\dist\\build-src\\util\\build\\optimizeRunner.js' ] }
Error: spawn java ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
build always "fails"
fs.js:951
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir 'C:\Users\ville_service\dist\buildOutput\app-packages'
    at Error (native)
    at Object.fs.readdirSync (fs.js:951:18)
    at visitFolderFiles (C:\Users\ville_service\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:617:18)
    at Object.cleanUncompressedSource (C:\Users\ville_service\AppData\Roaming\npm\node_modules\esri-wab-build\app\utilscripts.js:816:3)
    at Object.exports.copy (C:\Users\ville_service\AppData\Roaming\npm\node_modules\esri-wab-build\app\copyapp.js:21:17)
    at Object.exports.build (C:\Users\ville_service\AppData\Roaming\npm\node_modules\esri-wab-build\app\buildTool.js:132:14)
    at Object.exports.buildApp (C:\Users\ville_service\AppData\Roaming\npm\node_modules\esri-wab-build\app\remoteBuild.js:21:42)
    at Object.<anonymous> (C:\Users\ville_service\AppData\Roaming\npm\node_modules\esri-wab-build\app\build:12:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```
